# Generated by Django 3.2.8 on 2021-10-20 02:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_stuff', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fileupload',
            old_name='name',
            new_name='type',
        ),
    ]
